server:
  port: 8989

spring:
  application:
    name: service-miya

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    base-url: http://localhost:9411